# Generated by Django 5.2.4 on 2025-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text='Cutting Length in mm')),
                ('qty', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
            ],
        ),
    ]
